name: tuneyourvibe
favicon: null
layout_spectrum: 0
typography_spectrum: 0.77923
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0131ff'
    - '#0080ff'
    - '#01c3ff'
    - '#87c3ff'
    - '#01f3ff'
  brandStrength: 0.1875
  lightness: 0.9740282304119319
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
