name: tuneyourvibe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303a46'
    - '#6e8992'
    - '#4f6a73'
    - '#9ebfb8'
    - '#946862'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
