typography_spectrum: 0.7547
color:
  brandColors:
    - '#303a46'
    - '#6e8992'
    - '#4f6a73'
    - '#9ebfb8'
    - '#946862'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53794
analytics:
  google: null
  facebook: null
  twitter: null
name: tuneyourvibe
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Booking and Contact
    id: bc990681-14ea-46a7-b76c-a70a342550a2
    type: content
  - name: NES Health with Debbie Littrell Ventura
    id: eed0ed54-bc3d-472d-be6f-470c9fd02ac9
    type: content
  - name: Energy + Information = Life
    id: c03675e4-5619-455b-b665-73514a36f23f
    type: content
favicon: null
title: TuneYourVibe
purpose: []
