name: tuneyourvibe
favicon: null
layout_spectrum: 0.638409421313554
typography_spectrum: 0.5083069442771375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.358173152199015
  lightness: 0.9740282304119319
  saturation: 0.2628448763862252
  rhythmicContrast: 0.012450509937480092
purpose: []
