name: tuneyourvibe
favicon: null
layout_spectrum: 0.20188
typography_spectrum: 0.89797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303a46'
    - '#6e8992'
    - '#4f6a73'
    - '#9ebfb8'
    - '#946862'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
