name: tuneyourvibe
favicon: null
layout_spectrum: 0.4743
typography_spectrum: 0.76263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffffe'
    - '#e14900'
    - '#e2b433'
    - '#de0762'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
